/*
 * The MIT License
 * Copyright (c) 2018 Colin Frick
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package li.beryllium.wicket.fomantic.elements.flag;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * FlagType
 * <p/>
 * Type of the flag
 */
@AllArgsConstructor
@Getter
public enum FlagType {

    AFGHANISTAN("af"),
    ALAND_ISLANDS("ax"),
    ALBANIA("al"),
    ALGERIA("dz"),
    AMERICAN_SAMOA("as"),
    ANDORRA("ad"),
    ANGOLA("ao"),
    ANGUILLA("ai"),
    ANTIGUA("ag"),
    ARGENTINA("ar"),
    ARMENIA("am"),
    ARUBA("aw"),
    AUSTRALIA("au"),
    AUSTRIA("at"),
    AZERBAIJAN("az"),
    BAHAMAS("bs"),
    BAHRAIN("bh"),
    BANGLADESH("bd"),
    BARBADOS("bb"),
    BELARUS("by"),
    BELGIUM("be"),
    BELIZE("bz"),
    BENIN("bj"),
    BERMUDA("bm"),
    BHUTAN("bt"),
    BOLIVIA("bo"),
    BOSNIA("ba"),
    BOTSWANA("bw"),
    BOUVET_ISLAND("bv"),
    BRAZIL("br"),
    BRITISH_VIRGIN_ISLANDS("vg"),
    BRUNEI("bn"),
    BULGARIA("bg"),
    BURKINA_FASO("bf"),
    BURMA("mm"),
    BURUNDI("bi"),
    CAICOS_ISLANDS("tc"),
    CAMBODIA("kh"),
    CAMEROON("cm"),
    CANADA("ca"),
    CAPE_VERDE("cv"),
    CAYMAN_ISLANDS("ky"),
    CENTRAL_AFRICAN_REPUBLIC("cf"),
    CHAD("td"),
    CHILE("cl"),
    CHINA("cn"),
    CHRISTMAS_ISLAND("cx"),
    COCOS_ISLANDS("cc"),
    COLOMBIA("co"),
    COMOROS("km"),
    CONGO_BRAZZAVILLE("cg"),
    CONGO("cd"),
    COOK_ISLANDS("ck"),
    COSTA_RICA("cr"),
    COTE_DIVOIRE("ci"),
    CROATIA("hr"),
    CUBA("cu"),
    CYPRUS("cy"),
    CZECH_REPUBLIC("cz"),
    DENMARK("dk"),
    DJIBOUTI("dj"),
    DOMINICA("dm"),
    DOMINICAN_REPUBLIC("do"),
    ECUADOR("ec"),
    EGYPT("eg"),
    EL_SALVADOR("sv"),
    ENGLAND("gb eng"),
    EQUATORIAL_GUINEA("gq"),
    ERITREA("er"),
    ESTONIA("ee"),
    ETHIOPIA("et"),
    EUROPEAN_UNION("eu"),
    FALKLAND_ISLANDS("fk"),
    FAROE_ISLANDS("fo"),
    FIJI("fj"),
    FINLAND("fi"),
    FRANCE("fr"),
    FRENCH_GUIANA("gf"),
    FRENCH_POLYNESIA("pf"),
    FRENCH_TERRITORIES("tf"),
    GABON("ga"),
    GAMBIA("gm"),
    GEORGIA("ge"),
    GERMANY("de"),
    GHANA("gh"),
    GIBRALTAR("gi"),
    GREECE("gr"),
    GREENLAND("gl"),
    GRENADA("gd"),
    GUADELOUPE("gp"),
    GUAM("gu"),
    GUATEMALA("gt"),
    GUINEA_BISSAU("gw"),
    GUINEA("gn"),
    GUYANA("gy"),
    HAITI("ht"),
    HEARD_ISLAND("hm"),
    HONDURAS("hn"),
    HONG_KONG("hk"),
    HUNGARY("hu"),
    ICELAND("is"),
    INDIA("in"),
    INDIAN_OCEAN_TERRITORY("io"),
    INDONESIA("id"),
    IRAN("ir"),
    IRAQ("iq"),
    IRELAND("ie"),
    ISRAEL("il"),
    ITALY("it"),
    JAMAICA("jm"),
    JAN_MAYEN("sj"),
    JAPAN("jp"),
    JORDAN("jo"),
    KAZAKHSTAN("kz"),
    KENYA("ke"),
    KIRIBATI("ki"),
    KUWAIT("kw"),
    KYRGYZSTAN("kg"),
    LAOS("la"),
    LATVIA("lv"),
    LEBANON("lb"),
    LESOTHO("ls"),
    LIBERIA("lr"),
    LIBYA("ly"),
    LIECHTENSTEIN("li"),
    LITHUANIA("lt"),
    LUXEMBOURG("lu"),
    MACAU("mo"),
    MACEDONIA("mk"),
    MADAGASCAR("mg"),
    MALAWI("mw"),
    MALAYSIA("my"),
    MALDIVES("mv"),
    MALI("ml"),
    MALTA("mt"),
    MARSHALL_ISLANDS("mh"),
    MARTINIQUE("mq"),
    MAURITANIA("mr"),
    MAURITIUS("mu"),
    MAYOTTE("yt"),
    MEXICO("mx"),
    MICRONESIA("fm"),
    MOLDOVA("md"),
    MONACO("mc"),
    MONGOLIA("mn"),
    MONTENEGRO("me"),
    MONTSERRAT("ms"),
    MOROCCO("ma"),
    MOZAMBIQUE("mz"),
    NAMIBIA("na"),
    NAURU("nr"),
    NEPAL("np"),
    NETHERLANDS_ANTILLES("an"),
    NETHERLANDS("nl"),
    NEW_CALEDONIA("nc"),
    NEW_GUINEA("pg"),
    NEW_ZEALAND("nz"),
    NICARAGUA("ni"),
    NIGER("ne"),
    NIGERIA("ng"),
    NIUE("nu"),
    NORFOLK_ISLAND("nf"),
    NORTH_KOREA("kp"),
    NORTHERN_MARIANA_ISLANDS("mp"),
    NORWAY("no"),
    OMAN("om"),
    PAKISTAN("pk"),
    PALAU("pw"),
    PALESTINE("ps"),
    PANAMA("pa"),
    PARAGUAY("py"),
    PERU("pe"),
    PHILIPPINES("ph"),
    PITCAIRN_ISLANDS("pn"),
    POLAND("pl"),
    PORTUGAL("pt"),
    PUERTO_RICO("pr"),
    QATAR("qa"),
    REUNION("re"),
    ROMANIA("ro"),
    RUSSIA("ru"),
    RWANDA("rw"),
    SAINT_HELENA("sh"),
    SAINT_KITTS_AND_NEVIS("kn"),
    SAINT_LUCIA("lc"),
    SAINT_PIERRE("pm"),
    SAINT_VINCENT("vc"),
    SAMOA("ws"),
    SAN_MARINO("sm"),
    SANDWICH_ISLANDS("gs"),
    SAO_TOME("st"),
    SAUDI_ARABIA("sa"),
    SCOTLAND("gb sct"),
    SENEGAL("sn"),
    SERBIA("rs"),
    SEYCHELLES("sc"),
    SIERRA_LEONE("sl"),
    SINGAPORE("sg"),
    SLOVAKIA("sk"),
    SLOVENIA("si"),
    SOLOMON_ISLANDS("sb"),
    SOMALIA("so"),
    SOUTH_AFRICA("za"),
    SOUTH_KOREA("kr"),
    SPAIN("es"),
    SRI_LANKA("lk"),
    SUDAN("sd"),
    SURINAME("sr"),
    SWAZILAND("sz"),
    SWEDEN("se"),
    SWITZERLAND("ch"),
    SYRIA("sy"),
    TAIWAN("tw"),
    TAJIKISTAN("tj"),
    TANZANIA("tz"),
    THAILAND("th"),
    TIMORLESTE("tl"),
    TOGO("tg"),
    TOKELAU("tk"),
    TONGA("to"),
    TRINIDAD("tt"),
    TUNISIA("tn"),
    TURKEY("tr"),
    TURKMENISTAN("tm"),
    TUVALU("tv"),
    UAE("ae"),
    UGANDA("ug"),
    UKRAINE("ua"),
    UNITED_KINGDOM("gb"),
    UNITED_STATES("us"),
    URUGUAY("uy"),
    US_MINOR_ISLANDS("um"),
    US_VIRGIN_ISLANDS("vi"),
    UZBEKISTAN("uz"),
    VANUATU("vu"),
    VATICAN_CITY("va"),
    VENEZUELA("ve"),
    VIETNAM("vn"),
    WALES("gb wls"),
    WALLIS_AND_FUTUNA("wf"),
    WESTERN_SAHARA("eh"),
    YEMEN("ye"),
    ZAMBIA("zm"),
    ZIMBABWE("zw");

    private final String cssClass;

}
